version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: 
        name: install packages
        command: npm install
      
      - run:
        name: build
        command: npm build
