workflows:
  version: 2
  only_test:
    jobs:
      - test


version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: install
      - run: npm build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
